version: '3.1'

services:

  db:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=4565
      - POSTGRES_USER=app
      - POSTGRES_DB=db

    ports:
      - 5432:5432